### ISSUE TITLE
Unable to change the download location of the blockchain.

### ISSUE THREAD

**Issue by sifotes** [radix42/winzec#1]
Has this not been implemented yet? This would allow a lot more people to run full nodes.

E: Using symlinks does seem to work. Still, it's not a very user friendly work around.

**Comment by AtomicBones** [comment]
This is absolutely essential for those of us using Solid State Drives, I keep all my other Blockchains on RAID5 HDD's.
For now I've used Link Shell Extension to Hard Link the Folder in %AppData% but this really shouldn't be required when every other Wallet/Daemon has this ability already.

http://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html < Download if you need to do the same.

**Comment by trustfarm-dev** [comment]
I've trying following links.

https://social.technet.microsoft.com/Forums/windows/en-US/8b27ee00-07f0-4d83-b801-1be83ae21e88/moving-appdata-folder-to-a-diffrent-hard-drive?forum=w7itprogeneral

in command line.

mklink /d C:\Users\tfarmuser1\AppData\Roaming\Zcash D:\AppData\Roaming\Zcash

and make d:\AppData\Roaming\Zcash   and copy blockchain data to new folder

**Comment by gasperzupancic** [comment]
add something like this to c:\users\<username>\appdata\roaming\zcash\zcash.conf
datadir=d:\zcash
exportdir=d:\zcash

it works for me. no links needed.

**Comment by trustfarm-dev** [comment]
@sifotes  It would be very helpful to beginner or user who run wingui zcash,  @gasperzupancic 's experiences>
---
add something like this c:\users\<username>\appdata\roaming\zcash\zcash.conf
datadir=d:\zcash
exportdir=d:\zcash
---
