### ISSUE TITLE
2.0.1 crashes on start with non-ASCII username in %AppData% path

### ISSUE THREAD

**Issue by Affinity121** [radix42/winzec#17]
After updating to 2.0.1 it started to crash.

zcashd.exe crashes after winzec "Verifying proving key 2...". Last line in debug.log is "2018-10-25 22:14:05 Loading Sapling (Sprout Groth16) parameters from C:\Users\Администратор\AppData\Roaming\ZcashParams\sprout-groth16.params". If I run zcashd.exe manually, I get message "thread '<unnamed>' panicked at 'parameter path encoding error: Utf8Error { valid_up_to: 9, error_len: Some(1) }', libcore\result.rs:945:5''"

What is wrong with it?

**Comment by Affinity121** [comment]
Is this because of Russian 'Администратор' (Administrator) in path? Because I tried it on another PC without Russian, and it started okay.

**Comment by radix42** [comment]
yes, it is this bug in zcash 2.0.1:
https://github.com/zcash/librustzcash/issues/44

**Comment by Affinity121** [comment]
Any ideas will they fix it and when?

**Comment by radix42** [comment]
they are working on a fix

**Comment by radix42** [comment]
and I'm doing a build to test what is hopefully a fix...I'll post a link to a download to test in a while

**Comment by radix42** [comment]
ok, give this a try....download this zipfile:
https://zcash.dl.mercerweiss.com/zcash-win-v2.0.1a.zip
and copy the exe's in it into the folder:
C:\Program Files\winzec\app\

**Comment by radix42** [comment]
it should ask for admin rights and also ask if it should over-right two files and say yes

**Comment by radix42** [comment]
ok I took that release down, as it does NOT fix the issue :-(

the zcashd team is looking into other potential fixes

**Comment by radix42** [comment]
ok try the above with this zipfile:
https://zcash.dl.mercerweiss.com/zcash-win-v2.0.1b.zip

**Comment by radix42** [comment]
closing this issue, the new release, v2.0.1i that is up at Winzec.com has the fixed zcashd.exe in it
