### ISSUE TITLE
Remove unused t-addresses

### ISSUE THREAD

**Issue by ArturChek** [radix42/winzec#3]
Hi!

I was reinstalling zcach4win/winzec for several times, and each time on start it was generating me some t-address by default. Then I was importing private key and as a result I have:
- one address that i were using from the very first installation (it was generated by zcach4win),
- one for receiving change,
- and several autogenerated while each new installation.

So I have a proposal to add possibility to remove unused t-addresses.
I mean not address that using to received change, but which autogenerated and not using.

**Comment by radix42** [comment]
that behavior is from the underlying zcash daemon, you can't remove addresses
