### ISSUE TITLE
Issue when importing keys

### ISSUE THREAD

**Issue by TheDarknessEmperor** [radix42/winzec#5]
![image](https://user-images.githubusercontent.com/21046314/42451345-ebd68b0e-8354-11e8-9c80-b9ba7f07b39f.png)
Using keys exported from JAXX.
May be related to #4

**Comment by radix42** [comment]
yes this is a screenshot I was gonna ask for in that ticket, thank you for posting it

**Comment by gonzalezea** [comment]
Same error here. Trying to import WIF . Using v1.1.0-rc1 on W10 x64. No msg @ Zcash\debug.log

**Comment by gonzalezea** [comment]
Shame on me. I was just getting a wrong WIF key from my t1 address. After using correct key, everything works fine !!!.

**Comment by TheDarknessEmperor** [comment]
Waited until JAXX updated their client and sent it to a winzec made address fine. I have access to all my funds now. I would assume this is an issue on JAXX's end as they're know for having issues like this.
